### PR TITLE
Classify refactor

### PR DESCRIPTION
**Pull request by nexusapoorvacus**
The main change made to refactor classify.py is adding the method get_email_records. This method replaced output_phish_probabilities and returns a list of ResultRecord objects for a particular sender. ResultRecord objects contain all necessary information needed to output results to file in the classify functions, pretty_print and get_detector_contribution. A sender's emails are loaded into an Inbox object in get_email_records.

### CODE REVIEW

**Comment by mikeaboody** [comment]
With a test run, I received the following traceback:

Traceback (most recent call last):
  File "spear_phishing_detector.py", line 57, in <module>
    main()
  File "spear_phishing_detector.py", line 51, in main
    phish_detector.main()
  File "/Users/mdamiana/Desktop/phishing-research/common/phish_detector.py", line 322, in main
    detector.execute()
  File "/Users/mdamiana/Desktop/phishing-research/common/phish_detector.py", line 303, in execute
    self.generate_model_output()
  File "/Users/mdamiana/Desktop/phishing-research/common/phish_detector.py", line 285, in generate_model_output
    self.classifier.test_and_report()
  File "/Users/mdamiana/Desktop/phishing-research/common/classify.py", line 217, in test_and_report
    test_res = self.get_email_records(test_X, indx, root, test_indx, test_mess_id)
  File "/Users/mdamiana/Desktop/phishing-research/common/classify.py", line 361, in get_email_records
    assert (email["MESSAGE-ID"] == test_mess_id[i][0].strip(" ") or (test_mess_id[i][0].strip(" ") == 'None' and type(email["MESSAGE-ID"]) == type(None)))
AssertionError

**Comment by nexusapoorvacus** [comment]
What is the value of  email["MESSAGE-ID"] and test_mess_id[i][0].strip(" ") when this assertion error occurs?

**Comment by davidwagner** [comment]
I just pushed some code to print additional debugging information if the message ID doesn't match.  Try 'git pull' and run again, and show us the output?

(Also, I think I fixed a bug that was causing a spurious mismatch, by stripping both message IDs instead of just the second one.)

**Comment by davidwagner** [comment]
I looked through the code, and it looks good to me, and it runs fine on one large test mbox I tried.  Go ahead and merge when you are ready.

**Comment by mikeaboody** [comment]
With David's commits, it runs to completion.

**Comment by mikeaboody** [comment]
As well, there are no instances of "Message IDs don't match." in my log files.

**Pull request merged**
