### PR TITLE
ReceivedHeaderDetector improvements

### LINKED ISSUE #77: ReceivedHeadersDetector can probably be made a bit faster and save a bit more memory
In received_headers.py, createBreakdown() can be simpler.  It can probably be something like

    content = content.translate(None, '\n\r\t')
    r = re.search('from +(.*) +by', content)
    if r:
        return r.group(1).strip()
    r = re.search('from +(.*) +via', content)
    if r:
        return r.group(1).strip()
    ...

This will probably be faster.  It may also save memory, by not storing the rest of the breakdown.

### LINKED ISSUE #78: ReceivedHeaderDetector could be made more efficient
In received_header.py, the code for SenderReceiverProfile.createReceivedHeaderSequences() looks less efficient than it could be -- it looks like it has an O(n^2) algorithm where we could implement a O(n) time algorithm.

In particular, `if RHList not in seq_rh_from` will take O(n) time, where n is the length of the seq_rh_from list.  We then repeat that once per email.

It would be better to make seq_rh_from be a set (or dict).  Then checking membership and inserting into the set can be done in O(1) time.  This may require using a tuple instead of a list, but that's doable.

Same for classify().

### LINKED ISSUE #79: ReceivedHeaderDetector uses more memory than necessary
received_headers.py could be more memory-efficient.  It iterates through the emails and stores one Email object per email in `self[(sender,receiver)].emailList`.  Then, it iterates through those entries and adds one received-header-lists per email to `self[(sender,receiver)].received_header_sequences`.  It then stores emailList for the lifetime of the detector, even though it will never be used again.

This is unnecessary.  We could do this all in one loop, adding immediately to .received_header_sequences as we see each email.  This avoids the need to store .emailList and thus might save memory.

### PR DESCRIPTION
**Pull request by davidwagner**
Major refactoring of ReceivedHeaderDetector, with many changes:

* Saves memory by only storing one entry per mailpath seen, fixes #79
* Uses EDBag to speed up finding the edit distance to the most  similar mailpath in the sender profile, fixes #78
* More efficient parsing of received headers to pull out only the  part we actually use in this detector, fixes #77
* Other minor improvements: use built-in string operations rather  than regexps for performance, use iterators for cleaner code

### CODE REVIEW

**Comment by davidwagner** [comment]
Cc: @mikeaboody.  Check this to make sure it seems to work on your inbox and doesn't have stupid errors.

**Comment by mikeaboody** [comment]
It passes an eye check, I would prefer if @nexusapoorvacus also looked at it too. Let me try running it.

**Comment by mikeaboody** [comment]
When I run it, I get a similar cross validation. However, I find that it takes 90 seconds rather than the usual 75 seconds. Let's maybe run through this tomorrow before merging it.

**Comment by davidwagner** [comment]
Huh.  OK, I have a possible theory about why it might be taking longer.  Do you see in your logs (debug.log) anything of the form 'Large number of received header sequences'?  If so, can you paste those messages from (a) running without this PR, and (b) running with this PR?  @mikeaboody

**Comment by davidwagner** [comment]
Another thought: it's worth looking for logs "Enabling extra debugging..." and "Finished creating..." in progress.log and looking at those, too.  That'll enable us to see how long create_sender_profile() is taking, for senders with a lot of emails.

Also, we should compare the runtime of 'git checkout ef1b2d5' to 'git checkout e2dfa60'.  (i.e., not to 'git checkout master', as 'master' now has other changes that might be a confounding factor)  @mikeaboody

**Comment by mikeaboody** [comment]
Weird thing is when I try it now I get 51 seconds. Possible I had too many things open at the time too.

**Comment by davidwagner** [comment]
@mikeaboody ran this on his inbox and timed how long the entire program took:
On master: 61 seconds
On ef1b2d5: 65 seconds
On e2dfa60: 53 seconds

**Pull request merged**
